name: Build and Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare Deployment Directory
      run: |
        mkdir -p build/static
        mkdir -p build/templates
        cp -r static/* build/static/
        cp -r templates/* build/templates/
        cp README.md build/

        # Move index.html to the root of the build directory
        cp build/templates/index.html build/index.html
        # Optionally, you might also want to copy other files as needed

    - name: List files for debugging
      run: |
        ls -R build

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: static-site-artifact
        path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: static-site-artifact
