name: Build and Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare Deployment Directory
      run: |
        mkdir -p docs  # Create the docs directory where files will be copied
        cp -r static docs/static
        cp -r templates docs/templates
        cp index.py docs/
        cp README.md docs/
        cp requirements.txt docs/
        # Optionally copy other files as needed

    - name: List files for debugging
      run: |
        ls -R docs

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: flask-build-artifact
        path: ./docs  # Upload the docs directory

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: flask-build-artifact
